services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-web-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

  api:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-api-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
