services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-web-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: ["exec /app/src/Web/bin/Debug/net8.0/Web --urls http://0.0.0.0:5042"]

  api:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    image: escoles-api-dev
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: ["exec /app/src/Api/bin/Debug/net8.0/Api --urls http://0.0.0.0:7000"]
